"""init

Revision ID: 88e79cd1f074
Revises: 
Create Date: 2023-09-23 11:37:11.745023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88e79cd1f074'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
                    sa.Column('timezone', sa.Integer(), nullable=False),
                    sa.Column('notification_time', postgresql.ARRAY(sa.Integer()), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )
    op.create_table('calendar_event',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('owner_user_id', sa.Integer(), nullable=False),
                    sa.Column('invited_user_id', sa.Integer(), nullable=False),
                    sa.Column('appointment_time', sa.DateTime(), nullable=False),
                    sa.Column('duration', postgresql.INTERVAL(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['invited_user_id'], ['user.id'], ),
                    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )
    op.create_table('schedule',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('windows', postgresql.ARRAY(sa.Integer()), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule')
    op.drop_table('calendar_event')
    op.drop_table('user')
    # ### end Alembic commands ###
